require 'singleton'
require 'active_support/inflector'
require 'ruby-graphviz'

require 'rdepend/version'
require 'rdepend/state'
require 'rdepend/event'
require 'rdepend/event/root'
require 'rdepend/event/call'
require 'rdepend/event/return'
require 'rdepend/graph'
